backend:
  name: github
  repo: akaelisee/app-stack

media_folder: static/assets
public_folder: /assets

collections:

  - name: product
    label: Produit
    folder: products
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: price, required: false, label: Price}
      - { name: path, required: false, label: Path}

  - name: blog
    label: Article
    folder: articles
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}

      - label: librairy
        name: album-librairy
        widget: list
        required: true
        fields:
          - {label: Name, name: name, widget: string, required: true}
          - {label: Avatar, name: avatar, widget: image, required: true}

      - label: "City"
        name: "airport-code"
        widget: "select"
        options:
          - { label: "Chicago", value: "ORD" }
          - { label: "Paris", value: "CDG" }
          - { label: "Tokyo", value: "HND" }
  
 


        
    