backend:
  name: github
  repo: akaelisee/app-stack

media_folder: static/assets
public_folder: /assets

collections:

  #Chaussure 
  - name: shoe
    label: Chaussures 
    folder: src/templateKey/shoe
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
      - label: taille
        name: size
        widget: select
        required: true 
        multiple: true, 
        options: ["40", "41", "42", "43", "44"]
            
      - label: couleur
        name: color
        widget: select
        required: true      
        multiple: true, 
        options: ["Rouge", "noir", "gris", "blanc", "violet"]
  
      - label: "Created"
        name: "created"
        widget: "datetime"


  # Vêtement
  - name: clothe
    label: Vêtements 
    folder: src/templateKey/clothe
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
      - label: taille
        name: size
        widget: select
        required: true 
        multiple: true, 
        options: ["S", "M", "X", "xl", "xxl"]
            
      - label: couleur
        name: color
        widget: select
        required: true      
        multiple: true, 
        options: ["Rouge", "noir", "gris", "blanc", "violet"]

      - label: "Created"
        name: "created"
        widget: "datetime"


# Phone Tab
  - name: phontab
    label: Téléphone et Tablette 
    folder: src/templateKey/phontab
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
            
      - label: couleur
        name: color
        widget: select
        required: true      
        multiple: true, 
        options: ["Rouge", "noir", "gris", "blanc", "violet"]

      - label: "Created"
        name: "created"
        widget: "datetime"
  
  
  # Informatique and High tech
  - name: infotech
    label: Informatique et High tech 
    folder: src/templateKey/infotech
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
      - label: taille
        name: size
        widget: select
        required: true 
        multiple: true, 
        options: ["S", "M", "X", "xl", "xxl"]
            
      - label: couleur
        name: color
        widget: select
        required: true      
        multiple: true, 
        options: ["Rouge", "noir", "gris", "blanc", "violet"]
        
      - label: "Created"
        name: "created"
        widget: "datetime"

  # tv
  - name: tv
    label: Télevision
    folder: src/templateKey/tv
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
      - label: taille
        name: size
        widget: select
        required: true 
        multiple: true, 
        options: ["25", "35", "45", "65", "100"]
  
      - label: "Created"
        name: "created"
        widget: "datetime"

  
  # Bijou and sacs
  - name: bijsac
    label: Bijoux et Sacs
    folder: src/templateKey/bijsac
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: title, required: true, label: Titre}
      - { name: price, required: true, label: Prix}
      - { name: description, required: true, label: Description, widget: markdown}
      - { name: image, required: true, label: Image, widget: image}
      - { name: path, required: false, label: Path}
      - label: taille
        name: size
        widget: select
        required: true 
        multiple: true, 
        options: ["Grand", "Moyen", "petit"]
            
      - label: couleur
        name: color
        widget: select
        required: true      
        multiple: true, 
        options: ["Rouge", "noir", "gris", "blanc", "violet", "orange"]

      - label: "Created"
        name: "created"
        widget: "datetime"

 

  - name: blog
    label: Blog
    folder: src/templateKey/blog/entries
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    identifier_field: blogTitle
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "src/templateKey/blog/index.js"}
      -
        label: Titre
        name: title
        widget: string
      -
        label: Titre1
        name: title1
        widget: string
      -
        label: Auteur
        name: auteur 
        widget: string
      -
        label: 'Image'
        name: image
        widget: image
        allow_multiple: false
      -
        label: 'Image1'
        name: image1
        widget: image
        allow_multiple: false
      -
        label: Path
        name: path
        required: false
      -
        label: Description
        name: description
        widget: markdown
      -
        label: Description1
        name: description1
        widget: markdown
      -
        label: "Created"
        name: "created"
        widget: "datetime"